error:
thread 'tests::test_translation_complex' panicked at 'attempted to zero-initialize type `shaders::ffi::ShBuiltInResources`, which is invalid', library/core/src/panicking.rs:126:5
thread caused non-unwinding panic. aborting.
error: test failed, to rerun pass `--lib`